---
Name: mysite
---
SilverStripe\i18n\i18n:
  default_locale: en_NZ
SilverStripe\View\SSViewer:
  theme: base
  rewrite_hash_links: false
GDBackend:
  default_quality: 90
SilverStripe\Admin\LeftAndMain:
  cms_background: '#000000'
  cms_color: '#ffffff'
  cms_hover_background: '#000000'
  cms_active_background: '#000000'
  cms_active_color: '#ffffff'
  cms_drawer_background: '#000000'
BetterBrief\GoogleMapField:
  default_options:
    api_key: api_key_here
    show_search_box: true
    default_field_values:
      Latitude: '-40.900557'
      Longitude: '174.88597100000004'
      Zoom: 9
