---
Name: mysite
---
SilverStripe\i18n\i18n:
  default_locale: en_NZ
Database:
  name: ss_platotemplates
SilverStripe\View\SSViewer:
  theme: base
  rewrite_hash_links: false
GDBackend:
  default_quality: 90
SilverStripe\Admin\LeftAndMain:
  cms_background: '#000000'
  cms_color: '#ffffff'
  cms_hover_background: '#000000'
  cms_active_background: '#000000'
  cms_active_color: '#ffffff'
  cms_drawer_background: '#000000'
